### PR TITLE
Enhance Routing Capabilities

### PR DESCRIPTION
**Pull request by Chocolate4U**
# Description:
This PR will:
- Add "Geo Assets Provider" to routing settings
- Add Predefined rules for Iran
- Change Geo rules dynamically instead of hardcode
- Allow Geo files to download without Proxy

# Additional Information
#2517

### CODE REVIEW

**Comment by Chocolate4U** [comment]
I have optimized previous commits code and removed repetitive and redundant codes.
Also Geo Assets Provider now defaults to `Loyalsoldier` to be inline with previous app behavior.
domestic DNS now chnges based on pre defined rules, if  `Bypass Iran address then proxy` or `Bypassing LAN and Iran address then proxy` is selected it will set to `1.1.1.1` otherwise no change will happen.

**Comment by Chocolate4U** [comment]
@2dust @yuhan6665 

Please review.

**Comment by hawshemi** [comment]
**This is highly requested by users.**
@2dust @yuhan6665

**Comment by onetarh** [comment]
This is pretty nice.

**Comment by ralphneudorf** [comment]
Please add this feature for Iran.

**Comment by 2dust** [comment]
Thanks pr
This app mainly serves Chinese people

**Comment by hawshemi** [comment]
@2dust what? WOW!!!!!
Iran is second in the list and you don't care?

**Comment by hawshemi** [comment]
!!!!!!!!!

**Comment by mmrabbani** [comment]
This PR doesn't have ANY negative effect on Chinese users. Even the default settings remain for Chinese users. But this can help Iranians a lot. even Chinese users can switch between official and loyal soldier databases.
Please reconsider this decision.

**Comment by hawshemi** [comment]
@2dust This is ridiculous. Iranian users are number two on the users' list. so you don't care about them?
And what are the negative sides of this PR?

**Comment by mmrabbani** [comment]
@2dust 
NekoBox, as another chinese app, accepted similar PR.
https://github.com/MatsuriDayo/NekoBoxForAndroid/pull/331
Please reconsider accepting this PR.

**Comment by M03ED** [comment]
> Thanks pr
> This app mainly serves Chinese people

We didn't ask you to implement any feature , only thing we want to click and accept features that can help our people.

**Pull request closed without merging**
