### PR TITLE
[New Feature] UX enhancement - Reversed the order of server list

### PR DESCRIPTION
**Pull request by pouriaksrvi**
Fixed incorrect default order of server list as described in the issue https://github.com/2dust/v2rayNG/issues/2116
The default order was problematic for users who add new servers more frequently

### CODE REVIEW

**Comment by cuynu** [comment]
tks i will add in my project

**Comment by pouriaksrvi** [comment]
> tks i will add in my project

Sure, you're welcome. Add it ASAP please. It is necessary for all users but it is even more necessary for users who live in regions where having a long proxy list is needed.

**Comment by pouriaksrvi** [comment]
Read the **reviews in Google play** store.

There are some people complaining "Why the app works very well but it doesn't work after a month"
The problem is they are not aware of the reason, which I have explained in the issue https://github.com/2dust/v2rayNG/issues/2116 therefore they don't know the new servers which they add, get added to the bottom of the list. They just see the old servers which their test results are -1 at the top of the list and the list is too long to see its bottom end which healthy servers are added by them.

**Comment by 2dust** [comment]
thanks for your pr
Consider the case of batch import and subscription import？

**Comment by pouriaksrvi** [comment]
> thanks

You're welcome. 

> batch import and subscription import

Yes.
And the both of them have been tested successfully.

**Comment by 2dust** [comment]
I mean subscription should not be in reverse order

**Comment by pouriaksrvi** [comment]
> subscription should not be in reverse order

Imagine these servers:
1, 2, 3, 4, 5, 6, 7, 8, 9
Having 3, 4, 5, 6 imported from a subscription, having the order you suggested it will be like:
1, 2, **_6, 5, 4, 3_**, 7, 8, 9

Isn't that inconsistent? Imagine the user scrolling the list from the beginning to the end;
In the middle of the list, subscription-imported servers get seen sorted in the opposite order.
I'm sure it makes the user confused.

A list is sorted by time in descending order if and only if all its sub-lists are sorted in the same order.

I can change it if it is needed. Are you sure?

**Comment by pouriaksrvi** [comment]
The same reason for batch import:
Most of the times when the user copies servers from webpages or other sources, the newest servers get placed at the end of the list in the clipboard.
Therefore, they should be imported with the same order they have been copied, so the newest copied server gets put at the top of the list.
As explained in https://github.com/2dust/v2rayNG/issues/2116, the newest servers of the list, always have more chance to be healthy and working, so they should be the most accessible, in the default import order.

**Comment by pouriaksrvi** [comment]
I have added a bug fix commit, fixing subscription import order.
Now it works in the way you suggested.

**Comment by pouriaksrvi** [comment]
For batch import from clipboard, it is needed to import it in reversed order.
Imagine a webpage with this content:
```
post 1, 2020-02-01:
    some servers
post 2, 2020-02-02:
    some more servers
post 3, 2020-02-03:
    some more new servers
(more posts...)
```
Everyday, the older servers stop working or get blocked by the firewall and the admin provides some new servers in a new post.
The user randomly selects 100 recent posts by dragging the mouse cursor to copy some servers.
The latest posted servers should be imported to the top of the list because they are more likely to be alive, in tests and sorts.

Maybe users should not do it this way but they do.

**Comment by wangkong1122** [comment]
谁会节点设置教程教教我谢谢大哥

**Pull request merged**
