### PR TITLE
Target sdk 29

### PR DESCRIPTION
**Pull request by yuhan6665**
We will need to update target sdk to latest Android version this year. The main issue with the current code is that tun2socks binary will not be able to run from app folder. This is stated in:
https://issuetracker.google.com/issues/128554619#comment4

In this pull request, I've moved the tun2socks so that they can be copied to where .so lib is. A change is made to Go project with the new path. Note I've made minimum code change for this fix. You can probably substitute the aar.
If you are ok with it. I'm going to do more commits to clean up. Including the duplicated copy of tun2socks in app folder and its logic.

### CODE REVIEW

**Comment by likky** [comment]
使用您更新适配target 29版本编译生成的v2ray应用无法正常使用，不能访问谷歌等外网，节点没问题。
调试错误如下：
2020-08-25 15:38:40.101 14673-14673/? I/chatty: uid=10320 com.v2ray.ang:RunSoLibV2RayDaemon identical 1 line
2020-08-25 15:38:40.295 14673-14708/? I/GoLog: /data/app/com.v2ray.ang-nL-iwmaICe7x6zIsBOdqIg==/lib/arm64/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
2020-08-25 15:38:40.296 14673-14708/? I/GoLog: EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-nL-iwmaICe7x6zIsBOdqIg==/lib/arm64/tun2socks: no such file or directory
2020-08-25 15:38:40.417 14673-14713/? D/com.v2ray.ang: sendFd tries: 0
2020-08-25 15:38:40.418 14673-14713/? D/com.v2ray.ang: java.io.IOException: No such file or directory
2020-08-25 15:38:40.518 14673-14713/? D/com.v2ray.ang: sendFd tries: 1
2020-08-25 15:38:40.519 14673-14713/? D/com.v2ray.ang: java.io.IOException: No such file or directory
2020-08-25 15:38:40.719 14673-14713/? D/com.v2ray.ang: sendFd tries: 2
2020-08-25 15:38:40.720 14673-14713/? D/com.v2ray.ang: java.io.IOException: No such file or directory
2020-08-25 15:38:41.120 14673-14713/? D/com.v2ray.ang: sendFd tries: 3
2020-08-25 15:38:41.122 14673-14713/? D/com.v2ray.ang: java.io.IOException: No such file or directory
2020-08-25 15:38:41.922 14673-14713/? D/com.v2ray.ang: sendFd tries: 4
2020-08-25 15:38:41.923 14673-14713/? D/com.v2ray.ang: java.io.IOException: No such file or directory
2020-08-25 15:38:43.524 14673-14713/? D/com.v2ray.ang: sendFd tries: 5
2020-08-25 15:38:43.526 14673-14713/? D/com.v2ray.ang: java.io.IOException: No such file or directory
2020-08-25 15:38:44.508 14607-14878/? D/Linux: [Posix_connect Debug]Process com.v2ray.ang :10809 
2020-08-25 15:38:46.614 14607-14878/? D/Linux: [Posix_connect Debug]Process com.v2ray.ang :10809 
2020-08-25 15:38:46.726 14673-14713/? D/com.v2ray.ang: sendFd tries: 6
2020-08-25 15:38:46.728 14673-14713/? D/com.v2ray.ang: java.io.IOException: No such file or directory
2020-08-25 15:39:08.138 14673-14673/? D/com.v2ray.ang: SCREEN_OFF, stop querying stats

**Comment by yuhan6665** [comment]
@likky please make sure you get everything including the tun2socks binaries. After you compile the apk you should verify this inside your apk:
image

**Comment by likky** [comment]
Yes, aleady have the tun2socks binaries, but can't use. 
Android 10 phone and targetSdkVer=29

**Comment by yuhan6665** [comment]
hmm that is a weird issue. I can't reproduce on my Pixel device. You will need to check this folder on your phone
/data/app/com.v2ray.ang-nL-iwmaICe7x6zIsBOdqIg==/lib/arm64/
Does it contain a tun2socks file?

**Comment by likky** [comment]
下面两张图是v2ray的日志，图1是vivo手机，android10

图2是Pixel 3，android10，反应的是同一个问题。

**Comment by yuhan6665** [comment]
@likky unfortunately I can't troubleshoot this issue for you. You may need to play with the following code in this pr.

https://github.com/2dust/v2rayNG/blob/573079dd6c5ac152c43bee3d7e2c22d6f0a27767/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/Utils.kt#L451-L455

Essentially if you can return the correct folder holding tun2socks binary, it should work.
If you can figure out the issue, You are more than welcome to share your code :)

**Comment by yuhan6665** [comment]
@likky I gave it some thought and figured out a better way to get the path. Please try again with new version 6bee795

**Comment by likky** [comment]
@yuhan6665 I download the new version 6bee795 and generate apk.
When I install in my Vivo phone, it also has issues in following.
You can uninstall and reinstall the APK in following link.
链接：https://pan.baidu.com/s/1OW_6bKayLtI25WOQL7Dl5A 
提取码：2020

--------- beginning of main
08-28 10:09:35.196 E/com.v2ray.ang(12558): Not starting debugger since process cannot load the jdwp agent.
08-28 10:09:35.243 W/com.v2ray.ang(12558): type=1400 audit(0.0:157947): avc: denied { search } for name="bbkcore" dev="dm-3" ino=6160385 scontext=u:r:untrusted_app:s0:c68,c257,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0
08-28 10:09:35.253 W/com.v2ray.ang(12558): type=1400 audit(0.0:157949): avc: denied { search } for name="bbkcore" dev="dm-3" ino=6160385 scontext=u:r:untrusted_app:s0:c68,c257,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0
08-28 10:09:35.343 W/com.v2ray.ang(12558): type=1400 audit(0.0:157956): avc: denied { search } for name="bbkcore" dev="dm-3" ino=6160385 scontext=u:r:untrusted_app:s0:c68,c257,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0
--------- beginning of system
08-28 10:09:37.573 W/com.v2ray.ang(12558): type=1400 audit(0.0:158071): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20316 scontext=u:r:untrusted_app:s0:c68,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
08-28 10:10:31.263 W/com.v2ray.ang(12558): type=1400 audit(0.0:158086): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20316 scontext=u:r:untrusted_app:s0:c68,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
08-28 10:10:38.703 I/GoLog   (13204): [holder]
08-28 10:10:38.703 I/GoLog   (13204): /data/user/0/com.v2ray.ang/ArchIndep/holder
08-28 10:10:38.704 I/GoLog   (13204): Preparing Domain: 139.162.113.205:36788
08-28 10:10:38.704 I/GoLog   (13204): <nil>
08-28 10:10:38.704 I/GoLog   (13204): remove /data/user/0/com.v2ray.ang/holder: no such file or directory
08-28 10:10:38.704 I/GoLog   (13204): Prepare Result:
08-28 10:10:38.704 I/GoLog   (13204):  Domain: 139.162.113.205
08-28 10:10:38.704 I/GoLog   (13204):  Port: 36788
08-28 10:10:38.704 I/GoLog   (13204):  IPs: [139.162.113.205]
08-28 10:10:38.704 I/GoLog   (13204): <nil>
08-28 10:10:38.704 I/GoLog   (13204): [arm64]
08-28 10:10:38.704 I/GoLog   (13204): ArchDep/arm64
08-28 10:10:38.704 I/GoLog   (13204): /data/user/0/com.v2ray.ang/ArchDep/arm64/tun2socks
08-28 10:10:38.732 I/GoLog   (13204): remove /data/user/0/com.v2ray.ang/tun2socks: no such file or directory
08-28 10:10:38.732 I/GoLog   (13204): <nil>
08-28 10:10:38.732 I/GoLog   (13204): EnableLocalDNS: false
08-28 10:10:38.732 I/GoLog   (13204): ForwardIpv6: false
08-28 10:10:38.732 I/GoLog   (13204): DomainName: 139.162.113.205:36788
08-28 10:10:38.732 I/GoLog   (13204): loading v2ray config
08-28 10:10:38.733 I/GoLog   (13204): /data/app/com.v2ray.ang-XG5XadvHGEULl9HOhye0lg==/lib/arm64/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
08-28 10:10:38.735 I/GoLog   (13204): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-XG5XadvHGEULl9HOhye0lg==/lib/arm64/tun2socks: no such file or directory
08-28 10:10:38.735 I/GoLog   (13204): EscortRun Exit
08-28 10:10:38.741 I/GoLog   (13204): new v2ray core
08-28 10:10:38.742 I/GoLog   (13204): start v2ray core
08-28 10:10:38.744 I/GoLog   (13204): [Warning] v2ray.com/core: V2Ray 4.23.1 started
08-28 10:10:38.875 D/com.v2ray.ang(13204): sendFd tries: 0
08-28 10:10:38.877 D/com.v2ray.ang(13204): java.io.IOException: No such file or directory
08-28 10:10:38.978 D/com.v2ray.ang(13204): sendFd tries: 1
08-28 10:10:38.979 D/com.v2ray.ang(13204): java.io.IOException: No such file or directory
08-28 10:10:39.179 D/com.v2ray.ang(13204): sendFd tries: 2
08-28 10:10:39.181 D/com.v2ray.ang(13204): java.io.IOException: No such file or directory
08-28 10:10:39.581 D/com.v2ray.ang(13204): sendFd tries: 3
08-28 10:10:39.582 D/com.v2ray.ang(13204): java.io.IOException: No such file or directory
08-28 10:10:40.383 D/com.v2ray.ang(13204): sendFd tries: 4
08-28 10:10:40.384 D/com.v2ray.ang(13204): java.io.IOException: No such file or directory
08-28 10:10:40.560 I/GoLog   (13204): 127.0.0.1:47570 accepted //www.google.com:443 [proxy] 
08-28 10:10:40.679 I/GoLog   (13204): Using Prepared: 139.162.113.205
08-28 10:10:41.984 D/com.v2ray.ang(13204): sendFd tries: 5
08-28 10:10:41.986 D/com.v2ray.ang(13204): java.io.IOException: No such file or directory
08-28 10:10:45.187 D/com.v2ray.ang(13204): se

**Comment by yuhan6665** [comment]
How about the Pixel 3?

**Comment by yuhan6665** [comment]
@2dust thanks for merging the code!
However, as discussed with @likky, he found an issue that tun2socks binary is not copied to device. I couldn't reproduce the issue at the time. Today I read the doc again https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh
It clearly stated it only works for debug build. :(
So to fix the release build, we need to rename tun2socks as libtun2socks.so. See #577

**Comment by likky** [comment]
Good news, we find the issue. I will have a test today.

**Pull request merged**
