### PR TITLE
Update plugins in ```libs.versions.toml```

### PR DESCRIPTION
**Pull request by codewithtamim**
Update plugins in ```libs.versions.toml```

### CODE REVIEW

**Comment by codewithtamim** [comment]
uses the top level plugins in libs.versions.toml

**Comment by ghost** [comment]
Hello bro, thank you for your efforts. I had a question,If I'm not mistaken, the latest version of Kotlin is 2.0.21. Can't you change it to the latest version?!
https://kotlinlang.org/docs/releases.html
@CodeWithTamim

**Comment by codewithtamim** [comment]
> Hello bro, thank you for your efforts. I had a question,If I'm not mistaken, the latest version of Kotlin is 2.0.21. Can't you change it to the latest version?! https://kotlinlang.org/docs/releases.html @CodeWithTamim

Stable version?

**Comment by DECORATIVEFAMILYNG** [comment]
> > Hello bro, thank you for your efforts. I had a question,If I'm not mistaken, the latest version of Kotlin is 2.0.21. Can't you change it to the latest version?! https://kotlinlang.org/docs/releases.html @CodeWithTamim
> 
> Stable version?

The latest version is version 1.9 is 1.9.25 and the latest version is version 2.0 is 2.0.21. You can see the changes in each version in the link I posted.
https://kotlinlang.org/docs/releases.html

**Comment by ghost** [comment]
> > Hello bro, thank you for your efforts. I had a question,If I'm not mistaken, the latest version of Kotlin is 2.0.21. Can't you change it to the latest version?! https://kotlinlang.org/docs/releases.html @CodeWithTamim
> 
> Stable version?

The latest version is version 1.9 is 1.9.25 and the latest version is version 2.0 is 2.0.21. You can see the changes in each version in the link I posted.
https://kotlinlang.org/docs/releases.html

Since Kotlin 2.0.0, we ship the following types of releases:

Language releases (2. x. 0) that bring major changes in the language and include tooling updates. Released once in 6 months.

Tooling releases (2. x. 20) that are shipped between language releases and include updates in the tooling, performance improvements, and bug fixes. Released in 3 months after corresponding language release.

Bug fix releases (2. x. yz) that include bug fixes for tooling releases. There is no exact release schedule for these releases.

Lastet Stable version

GitHub Project Kotlin link:

https://github.com/JetBrains/kotlin/releases/tag/v2.0.21

**Comment by codewithtamim** [comment]
done

**Pull request merged**
