### PR TITLE
Refactor Stream Security Visibility Logic in ServerActivity

### PR DESCRIPTION
**Pull request by codewithtamim**
Refactored the stream security visibility handling logic in ServerActivity to remove redundant code and improve readability. Used a map to control visibility for different views, ensuring cleaner and more maintainable code.

### CODE REVIEW

**Comment by 2dust** [comment]
Lost
```
container_sni?.visibility = View.GONE
container_fingerprint?.visibility = View.GONE
```

**Comment by codewithtamim** [comment]
wait for it

**Comment by 2dust** [comment]
There are three values here, null, TLS, and reality.

**Comment by codewithtamim** [comment]
check now

**Comment by codewithtamim** [comment]
will do a new pr, something is wrong in my github desktop

**Pull request closed without merging**
