### PR TITLE
fix freezing UI in MainActivity, #2726 

### PR DESCRIPTION
**Pull request by mosayeb-a**
when the reloadServer fun is called every time which onResume is called, the same servers reload again. so it cause performance issue.

### CODE REVIEW

**Comment by 2dust** [comment]
If the background service updates the server list, how to refresh the interface?

**Comment by mosayeb-a** [comment]
I wrote a quick fix to solve this issue. But I think this project needs a lot of refactoring. Other solutions can be implemented which consume much less memory(RAM) or resourse  and are maintainable, but these solution require a lot of refactoring.

now it's look like this:

https://github.com/2dust/v2rayNG/assets/108512702/cceda59f-e688-48ce-b22d-2d29935337c1

**Comment by mosayeb-a** [comment]
Why do you close it without merging it? It's a bad fix ? Please give more
information.

**Comment by mosayeb-a** [comment]
Could you give me more explanation about background service which can change
the server list?

**Pull request closed without merging**
