### PR TITLE
Added CDN IP Scanner

### PR DESCRIPTION
**Pull request by vfarid**
I added a CDN clean IP scanner to the app in order to test configs behind a CDN (Cloudflare for now) and find best IPs of the CDN for the user's ISP.

Look at the below video to see how it works:

https://github.com/2dust/v2rayNG/assets/23278340/52a44992-0568-4d00-b8a6-69016cff5c46

### CODE REVIEW

**Comment by mostafa5804** [comment]
واقعا دست مریزاد👍

**Comment by XRaySup** [comment]
That really useful.

**Comment by Piroz021** [comment]
Very well...thank you ❣️

**Comment by researcher952** [comment]
best👌

**Comment by ErFUN-KH** [comment]
Good job Vahid 👏🏻

**Comment by mfat** [comment]
Please add this to the app.

**Comment by NIMADROID** [comment]
It's Good ability for knock GFW

**Comment by amir323b** [comment]
That really useful.

**Comment by rickyivan** [comment]
waiting for this option

**Comment by Rezasaai** [comment]
You are really hot man, great as always

**Comment by Petrichor998** [comment]
This is really cool man .i hope they add it in the next update 🤞

**Comment by H4m3d84** [comment]
دمت گرم عالی👍

**Comment by 1384amir** [comment]
ایول 👌🙌

**Comment by an0nymousteam** [comment]
Amazing💥

**Comment by emad1381** [comment]
It's great

**Comment by hadrixxx** [comment]
Wonderful

**Comment by ashkannourm** [comment]
Thanks
Please add this feature to released app

**Comment by navidtaji** [comment]
Thanks for adding new features to the app

**Comment by ahrari123** [comment]
😍😍🤩🤩

**Comment by ghost** [comment]
😀👍

**Comment by mzarchi** [comment]
It's perfect ❤️

**Comment by mobohes** [comment]
Amazing😍

**Comment by sarabbafrani** [comment]
Thanks bro 🙏

**Comment by joiniran** [comment]
Nice job Vahid

**Comment by Bigalvat** [comment]
Pls Add

**Comment by mohammad20101368** [comment]
Hello, this update is very useful, thank you

**Comment by maysamch** [comment]
> I added a CDN clean IP scanner to the app in order to test configs behind a CDN (Cloudflare for now) and find best IPs of the CDN for the user's ISP.
> 
> Look at the below video to see how it works:
> 
>  Screen_Recording_20240310_205624_v2rayNG.2.mp4

How can we upvote

**Comment by Baashoom** [comment]
👍

**Comment by pourif** [comment]
Fantastic 😍

**Comment by Saeedaares** [comment]
bravo bro

**Comment by emisemok** [comment]
ممنون ک هستی🙏

**Comment by yaghobmn** [comment]
Great

**Comment by abaqqal** [comment]
❤️

**Comment by arashfereydony** [comment]
Really Useful 👍

**Comment by mehdi2004usa** [comment]
بسیار عالی٫ممنون از زحمتاتتون

**Comment by gransa** [comment]
👍👍👍

**Comment by maysamch** [comment]
ای بابا خوب یکی بگه چطور باید آپوت کنیم که این قابلیت به v2ray اضافه بشه

**Comment by mostafaSataki** [comment]
Please add this feature.

**Comment by Fatifan** [comment]
Really useful, thank you👌🏻

**Comment by freeman6869** [comment]
Very good🌹🌹

**Comment by m3hdiclub** [comment]
Karet doroste💪♥️

**Comment by fooadkhan** [comment]
Really useful add this feature.

**Comment by saeedsji** [comment]
Really useful add this feature.

**Comment by Kulumi6585** [comment]
Very nice 👍

**Comment by Daneshpico** [comment]
Please add this to the app❤️❤️

**Comment by d4rk-n0153** [comment]
👍

**Comment by Khoofo1983** [comment]
Perfect

**Comment by mohamad15516** [comment]
Please add this possibility to the application. Thank you❤️👍

**Comment by sandifordmani** [comment]
عالی ممنون

**Comment by MP1370** [comment]
> I added a CDN clean IP scanner to the app in order to test configs behind a CDN (Cloudflare for now) and find best IPs of the CDN for the user's ISP.
> 
> Look at the below video to see how it works:
> 
>  Screen_Recording_20240310_205624_v2rayNG.2.mp4

That's amazing 👏

**Comment by MP1370** [comment]
That is awesome 👌

**Comment by smehdid** [comment]
BEST idea ....  tanx

**Comment by dani96102** [comment]
Wow...great

**Comment by raminhafezi** [comment]
Good patch to be able to scan IP range

**Comment by faravps2020** [comment]
That really useful.

**Comment by ebrahimirad** [comment]
Exciting feature, this is awesome 👌

**Comment by mahdibarati0** [comment]
آقا فرید احسنت حرفی برای گفتن نیست این قدر خوب و عالی 
چشم اونایی که نمیتونن ببینم کور....به امید خبرهای خوبه دیگه

**Comment by Aydakk** [comment]
دست مریزاد❤️🙏

**Comment by pashaee** [comment]
Useful
Nice

**Comment by MrRezaB** [comment]
> ای بابا خوب یکی بگه چطور باید آپوت کنیم که این قابلیت به v2ray اضافه بشه

لایک کن داداش

**Comment by MrRezaB** [comment]
عالی وحید جان🙏🙏❤️

**Comment by hamidrrz** [comment]
👍

**Comment by Aydakk** [comment]
دست مریزاد❤️🙏

**Comment by Aydakk** [comment]
دست مریزاد❤️🙏

**Comment by Aydakk** [comment]
سلام در گت هاب واستون کامنت گذاشتم ولی چه جوری اینکه گفتی در ویتوری راه
بندازیم

در تاریخ دوشنبه 11 مارس 2024، 0:08 MrRezaB ***@***.***> نوشت:

**Comment by king2373** [comment]
عاالییی

**Comment by mnakhaei** [comment]
Nice feature

**Comment by nzrmohammad** [comment]
ایول دمت گرم واقعا این خیلی لازم

**Comment by mikeesierrah** [comment]
عالیه

**Comment by ghost** [comment]
Excellent👏👏
One of the most practical ways to bypass cruel filtering in Iran

**Comment by MMAGP** [comment]
Fantastic 🤩🤩

**Comment by Mohamad-beigy** [comment]
😍

**Comment by hesam13733** [comment]
Awesome

**Comment by ffallah** [comment]
Upvote 👍

**Comment by SoroushImanian** [comment]
> I added a CDN clean IP scanner to the app in order to test configs behind a CDN (Cloudflare for now) and find best IPs of the CDN for the user's ISP.
> 
> Look at the below video to see how it works:
> 
>  Screen_Recording_20240310_205624_v2rayNG.2.mp4

Thanks ❤️🥰🙏🏻

**Comment by reza4fprm** [comment]
Good👌👌

**Comment by mhdmzd** [comment]
Awesome 👍🏻

**Comment by FaRaZ-M** [comment]
Well done 👏

**Comment by Ehsan7156** [comment]
Useful and valuable 🤯🤯🤯🤯
Tnx

**Comment by Alexander-McQuen** [comment]
Dear Vahid ,thats amazing, 
hopefully @2dust take it to the action, 

best regards

**Comment by M0HMD-M** [comment]
Amazing🙌🤩

**Comment by Rohollah1986** [comment]
so awesome

**Comment by unrated1** [comment]
Very goof idea

**Comment by rezasadighpour** [comment]
😋😋🥰🩷💖❤️‍🩹

**Comment by rezaamirian** [comment]
very useful

**Comment by saeedfweb** [comment]
useful  idea،, thanks

**Comment by mojtaba6393** [comment]
درود بر شما احسنت

**Comment by miladsa740** [comment]
best

**Comment by hamid-ra** [comment]
یاشا

**Comment by jimbo5465** [comment]
Such a brilliant idea 💡

**Comment by Williamgazanf** [comment]
Excellent👏👏
One of the most practical ways to bypass cruel filtering in Iran

**Comment by Williamgazanf** [comment]
That really useful.

**Comment by javidshah2** [comment]
### Defeat the dictatorial government of China and Russia in limiting the Internet with this feature.

✌🏻✌🏻

**Comment by aminkokabi** [comment]
Thank you 🙏

**Comment by The-Binary-0-1** [comment]
That's brilliant! 👌

**Comment by 2dust** [comment]
You can develop a separate tool app for this function.

**Comment by qar4al** [comment]
It is very great and practical 👏👍

**Comment by younes2513** [comment]
wooowww...It is very great and practical

**Comment by javidshah2** [comment]
### Please add this feature 🙏🙏🙏

**Comment by Glimpser-zz** [comment]
Upvote 👍

**Comment by ahmadsheikhi89** [comment]
واقعا ممنون بابت زحماتی که میکشی 🙏

**Comment by r-sbr90** [comment]
Good job

**Comment by vfarid** [comment]
> You can develop a separate tool app for this function.

It would be useful when is integrated to the vpn client app and i had some incomplete development to apply clean ips to the possible configs so the whole process could be very useful for non-it users who are not very familiar with this definitions and only wanted to stay connected.
Anyway its your descision, and thanks for your great work.

**Comment by MajMajVPN** [comment]
Upvote

**Comment by MjKhani** [comment]
very good 🤩👍

**Comment by cjmahdi2** [comment]
Vahid is the best

**Comment by matin-alizadeh** [comment]
This option is very helpful.
Please add this in next release.

**Comment by MH140000** [comment]
Please add to v2ray ng app.

**Comment by Mahyadel** [comment]
👏👏👏👏👏

**Comment by metasina3** [comment]
Yesss add it plz

**Comment by ircfspace** [comment]
The v2rayng app has become one of the most utilized clients among Iranian users, playing a crucial role in the fight against and circumvention of imposed censorship barriers. Vahid Farid has invested a significant amount of time in developing and adding a highly practical tool for the 80 million-strong Iranian community. 

@2dust, **Why don't you show a little flexibility yourselves?**

**Comment by babackGeek** [comment]
It is very useful and we request you to add this function in the application.

**Comment by rahman8521** [comment]
It is very useful

**Comment by Raad63** [comment]
👍

**Comment by AbbasRangBast** [comment]
👍👍👍🙏🙏🙏🌹🌹🌹

**Comment by msigari** [comment]
perfect and useful

**Comment by whooooooooami** [comment]
Upvote

**Comment by Arixolin** [comment]
دس خوش عالی🔥♥️

**Comment by Arixolin** [comment]
Thank you Mr vahid🔥🔥🔥

**Comment by Wolf6470** [comment]
❤️❤️❤️

**Comment by Wolf6470** [comment]
very useful

**Comment by mmahdiyaramm** [comment]
Thank all friends

**Comment by ssm-mjk** [comment]
Good job🌹🌹

**Comment by mehranbarbar** [comment]
Please add this feature 🙏🙏🙏

**Comment by mehranbarbar** [comment]
Please add this feature 🙏🙏🙏

**Comment by Sohrab1999** [comment]
To the feedom of internet

**Comment by NIKJOO** [comment]
A very efficient feature to facilitate internet access without censorship in one package

**Comment by farzadasg61** [comment]
👍

**Comment by holms2012** [comment]
👍

**Comment by mmarjani** [comment]
👍

**Comment by xJuniorProgrammer** [comment]
useful function

**Comment by yeonvoo** [comment]
👍

**Comment by QMahyar** [comment]
please add

**Comment by miladnasiri2479** [comment]
This is special feature for anti filter👏👏

**Comment by Fatifan** [comment]
Mr.vahid can you add mixed sni support in this app? (For load balancing) 
@vfarid

**Comment by hameyahich** [comment]
very nice. دمت گرم

**Comment by BugHunter021** [comment]
TNX Bro

**Comment by Arashch405** [comment]
ضمن خسته نباشید.بله موافقم

**Comment by nimapolpro** [comment]
That's really good

**Comment by saeid9999** [comment]
عالی

**Comment by Aydakk** [comment]
❤️🙏

**Comment by yazdaniyan73** [comment]
nice job

**Comment by omiddada** [comment]
عالیه

**Comment by hamidhashemzadeh12** [comment]
Please add

**Comment by Fatifan** [comment]
دوستان این درخواست رد شده لطفا دیگه اینجا کامنت نذارید

**Comment by Fatifan** [comment]
Friends, this request has been rejected, please do not leave comment here

**Comment by Sleepy1195** [comment]
عالی

**Comment by pooriya5** [comment]
لطفا این قابلیت را اضافه کنید..متشکرم وخسته نباشید..بسیار عالی که به فکر پیشرفت هستید

**Comment by Teteration** [comment]
Good job.
useful function!
please merge it!

**Comment by 2dust** [comment]
https://github.com/2dust/D-Tools
It's already a new app on its own

**Comment by vfarid** [comment]
> https://github.com/2dust/D-Tools It's already a new app on its own

Thanks @2dust, but it is not useful without config. What i sent you as a PR was to test IP inside config using real delay method. There are existing tools to test clean ips but none of them use real delay and if you add this functionality to this app it will be very useful and the results will be different.
I again ask you let me add this functionality to this app, there is no negative impact at all.

Thank you.

**Comment by 2dust** [comment]
> > https://github.com/2dust/D-Tools It's already a new app on its own
> 
> Thanks @2dust, but it is not useful without config. What i sent you as a PR was to test IP inside config using real delay method. There are existing tools to test clean ips but none of them use real delay and if you add this functionality to this app it will be very useful and the results will be different. I again ask you let me add this functionality to this app, there is no negative impact at all.
> 
> Thank you.

https://github.com/2dust/D-Tools
This app contains a sing-box core
so it's easy to implement a true connection latency test
It will take some time to perfect it.

**Comment by vfarid** [comment]
> > > https://github.com/2dust/D-Tools It's already a new app on its own
> > 
> > 
> > Thanks @2dust, but it is not useful without config. What i sent you as a PR was to test IP inside config using real delay method. There are existing tools to test clean ips but none of them use real delay and if you add this functionality to this app it will be very useful and the results will be different. I again ask you let me add this functionality to this app, there is no negative impact at all.
> > Thank you.
> 
> https://github.com/2dust/D-Tools This app contains a sing-box core so it's easy to implement a true connection latency test It will take some time to perfect it.

I know many feature can be added to this new app and know what you mean, but having an option inside v2rayng to find best ips for configs will be more useful while after scan we can replace clean ips to related configs so that after using the scanner the user can apply results to their configs using a single click.
For those who are less familiar with IT/mobile apps this would be very useful. Thats why i try to convince you add this feature to main app. Also fragment scanner is the same story.

**Comment by vfarid** [comment]
> > > > https://github.com/2dust/D-Tools It's already a new app on its own
> > > 
> > > 
> > > Thanks @2dust, but it is not useful without config. What i sent you as a PR was to test IP inside config using real delay method. There are existing tools to test clean ips but none of them use real delay and if you add this functionality to this app it will be very useful and the results will be different. I again ask you let me add this functionality to this app, there is no negative impact at all.
> > > Thank you.
> > 
> > 
> > https://github.com/2dust/D-Tools This app contains a sing-box core so it's easy to implement a true connection latency test It will take some time to perfect it.
> 
> I know many feature can be added to this new app and know what you mean, but having an option inside v2rayng to find best ips for configs will be more useful while after scan we can replace clean ips to related configs so that after using the scanner the user can apply results to their configs using a single click. For those who are less familiar with IT/mobile apps this would be very useful. Thats why i try to convince you add this feature to main app. Also fragment scanner is the same story.

@2dust i belive both ip scanner and fragment scanner will improve usability and user experience of v2rayng and will be a benchmark for other apps to add such features accordingly, without any negative impact. Just say: ok, lets do it :)

**Pull request closed without merging**
