### PR TITLE
Added "Auto Test and Connect" Feature

### PR DESCRIPTION
**Pull request by omid-aram**
In Settings, there is now a new checkbox called "Auto Test and Connect". By enabling this feature, it will test the current connected configuration every 15 minutes, and if it fails, it will run "Real delay all configuration" and connect to the first (quickest) config that returns a positive result.

### CODE REVIEW

**Comment by omid-aram** [comment]
Hello, everyone. I had trouble switching between suitable configurations when I went to other locations. For example, when I was at home, some configurations worked, but others only worked on my office wifi or my mobile data. So I had to test these configurations manually, which I frequently forgot to do, resulting in disconnectivity. So I added a new feature to test periodically and, if there is no real connection, attempt to connect to the appropriate configuration by doing "Real delay all configuration".

AutoTestConnect

**Comment by hossinasaadi** [comment]
good PR. i think you can use `leastPing` BalancerStrategy instead of this functions.
links :
[Balancer](https://xtls.github.io/config/routing.html#balancerobject)
[observatory](https://xtls.github.io/config/metrics.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)


example :
```json

"balancers": [
  {
    "tag": "balancer",
    "selector": [
      "portal-1",
      "portal-2",
      "portal-3" 
    ],
    "strategy": {
      "type": "leastPing"
    },
    "fallbackTag": "portal-2"
  }
],
"observatory": {
  "subjectSelector": [
    "portal-1",
    "portal-2", 
    "portal-3"
  ],
  "probeURL": "https://www.google.com/generate_204",
  "probeInterval": "15m",
  "enableConcurrency": false
}

```

**Comment by omid-aram** [comment]
> good PR. i think you can use `leastPing` BalancerStrategy instead of this functions. links : [Balancer](https://xtls.github.io/config/routing.html#balancerobject) [observatory](https://xtls.github.io/config/metrics.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> 
> example :
> 
> ```json
> "balancers": [
>   {
>     "tag": "balancer",
>     "selector": [
>       "portal-1",
>       "portal-2",
>       "portal-3" 
>     ],
>     "strategy": {
>       "type": "leastPing"
>     },
>     "fallbackTag": "portal-2"
>   }
> ],
> "observatory": {
>   "subjectSelector": [
>     "portal-1",
>     "portal-2", 
>     "portal-3"
>   ],
>   "probeURL": "https://www.google.com/generate_204",
>   "probeInterval": "15m",
>   "enableConcurrency": false
> }
> ```

Thank you for pointing this out.

**Comment by joiniran** [comment]
Nice job

**Comment by keyvooon** [comment]
useful👍

**Comment by 2dust** [comment]
> good PR. i think you can use `leastPing` BalancerStrategy instead of this functions. links : [Balancer](https://xtls.github.io/config/routing.html#balancerobject) [observatory](https://xtls.github.io/config/metrics.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> 
> example :
> 
> ```json
> "balancers": [
>   {
>     "tag": "balancer",
>     "selector": [
>       "portal-1",
>       "portal-2",
>       "portal-3" 
>     ],
>     "strategy": {
>       "type": "leastPing"
>     },
>     "fallbackTag": "portal-2"
>   }
> ],
> "observatory": {
>   "subjectSelector": [
>     "portal-1",
>     "portal-2", 
>     "portal-3"
>   ],
>   "probeURL": "https://www.google.com/generate_204",
>   "probeInterval": "15m",
>   "enableConcurrency": false
> }
> ```

Agree with this , please use the core function

**Comment by Pun-Pun-03** [comment]
> Hello, everyone. I had trouble switching between suitable configurations when I went to other locations. For example, when I was at home, some configurations worked, but others only worked on my office wifi or my mobile data. So I had to test these configurations manually, which I frequently forgot to do, resulting in disconnectivity. So I added a new feature to test periodically and, if there is no real connection, attempt to connect to the appropriate configuration by doing "Real delay all configuration".
> 
> AutoTestConnect

Can you Add a range slider for Duration in second(s) under this check box? I think 15 min isn't good because in 20 or 30 seconds user realises connection is curropted and reconnect VPN manually.
image

**Comment by thefatedefeater** [comment]
Great Idea!
I Hope They Implant Such Wonderful Function

**Pull request closed without merging**
