### PR TITLE
optimize(ui):adjust color

### PR DESCRIPTION
**Pull request by FranzKafkaYu**
adjust color  for better UI,related Issue：https://github.com/2dust/v2rayNG/issues/3100

### CODE REVIEW

**Comment by Fatifan** [comment]
I think #747474 is too dark and the black color (connection status) is not visible on it, I suggest #cdcdcd .

**Comment by 2dust** [comment]
Everyone has different aesthetics
Please provide a picture after you have modified it

**Comment by Fatifan** [comment]
@2dust
 Do you believe that this is not a bug? If not, I'm pretty sure that #cdcdcd is a good choice for the "colorPrimary" tag and the black text and white icons will be visible on it but I'm not able to modify the code and provide a picture of the result, but you can try this.

**Comment by FranzKafkaYu** [comment]
This PR is to solve the problem that the navigation bar at the bottom is less clearly visible.the following picture is the latest V2rayNG version in my XiaoMi Rednote 11 Pro+：
image

**Comment by Fatifan** [comment]
@FranzKafkaYu 
I know and I had written #3100 myself, but the color you suggested in this PR is too dark and the black text above the icons cannot be visible on it.

**Comment by FranzKafkaYu** [comment]
> @FranzKafkaYu I know and I had written #3100 myself, but the color you suggested in this PR is too dark and the black text above the icons cannot be visible on it.

I used AVD to test,the black text seems all right,just like this：

**Pull request closed without merging**
