### PR TITLE
Build and cache libtun2socks and libv2ray

### PR DESCRIPTION
**Pull request by UjuiUjuMandan**
- https://github.com/2dust/AndroidLibV2rayLite/pull/42

The latest build failed, probably try increasing heap size in `org.gradle.jvmargs`.

### CODE REVIEW

**Comment by 2dust** [comment]
fdroid's requirements are a bit too much. It will be a waste of time to compile these libraries every time.

**Comment by UjuiUjuMandan** [comment]
It can be cached anyway. The two upstream repo hasn't changed for a long time. Just don't put the binaries inside git repo.

Wait a moment.

**Comment by UjuiUjuMandan** [comment]
libv2ray.aar can also be cached BTW.

From my observation, the building of libtun2socks takes little time, but the former is not.

**Comment by UjuiUjuMandan** [comment]
Cache enabled, it looks like this: 

- https://github.com/UjuiUjuMandan/v2rayNG/actions/runs/12444877323/job/34745589207

https://github.com/2dust/AndroidLibV2rayLite/pull/42 should be merged before this, it needs submodule metadata to calculate cache key.

**Pull request merged**
