### PR TITLE
Add Luri Bakhtiari language translations

### PR DESCRIPTION
**Pull request by hosseinabaspanah**
Hello, please add the language translation file of Luri Bakhtiari to the program...
@2dust

### CODE REVIEW

**Comment by hosseinabaspanah** [comment]
Hello, is there problem to add new translations to the program???

**Comment by codewithtamim** [comment]
> Hello, is there problem to add new translations to the program???

Update the locale getLocale() function and also the Language enum, otherwise it will not function fully

**Comment by hosseinabaspanah** [comment]
> > Hello, is there problem to add new translations to the program???
> 
> Update the locale getLocale() function and also the Language enum, otherwise it will not function fully

It is better to be done by @2dust

**Comment by codewithtamim** [comment]
> > > Hello, is there problem to add new translations to the program???
> > 
> > 
> > Update the locale getLocale() function and also the Language enum, otherwise it will not function fully
> 
> It is better to be done by @2dust

You have to make your pr functional otherwise it's of no use.

**Comment by hosseinabaspanah** [comment]
> > > > Hello, is there problem to add new translations to the program???
> > > 
> > > 
> > > Update the locale getLocale() function and also the Language enum, otherwise it will not function fully
> > 
> > 
> > It is better to be done by @2dust
> 
> You have to make your pr functional otherwise it's of no use.

I'm afraid to destroy the project with changes in the source code because I'm not very familiar with working with files in GitHub...

**Comment by codewithtamim** [comment]
> > > > > Hello, is there problem to add new translations to the program???
> > > > 
> > > > 
> > > > Update the locale getLocale() function and also the Language enum, otherwise it will not function fully
> > > 
> > > 
> > > It is better to be done by @2dust
> > 
> > 
> > You have to make your pr functional otherwise it's of no use.
> 
> I'm afraid to destroy the project with changes in the source code because I'm not very familiar with working with files in GitHub...

Okay after it merges I will do, what's the language and country?

**Comment by hosseinabaspanah** [comment]
> > > > > > Hello, is there problem to add new translations to the program???
> > > > > 
> > > > > 
> > > > > Update the locale getLocale() function and also the Language enum, otherwise it will not function fully
> > > > 
> > > > 
> > > > It is better to be done by @2dust
> > > 
> > > 
> > > You have to make your pr functional otherwise it's of no use.
> > 
> > 
> > I'm afraid to destroy the project with changes in the source code because I'm not very familiar with working with files in GitHub...
> 
> Okay after it merges I will do, what's the language and country?

Thank you for your help and understanding...
Only the bqi language code is enough and there is no need for the country code...

If the country code is mandatory, consider "ir"...

**Comment by hosseinabaspanah** [comment]
The name of the language is "لۊری بختیاری"

**Comment by codewithtamim** [comment]
> > > > > > > Hello, is there problem to add new translations to the program???
> > > > > > 
> > > > > > 
> > > > > > Update the locale getLocale() function and also the Language enum, otherwise it will not function fully
> > > > > 
> > > > > 
> > > > > It is better to be done by @2dust
> > > > 
> > > > 
> > > > You have to make your pr functional otherwise it's of no use.
> > > 
> > > 
> > > I'm afraid to destroy the project with changes in the source code because I'm not very familiar with working with files in GitHub...
> > 
> > 
> > Okay after it merges I will do, what's the language and country?
> 
> Thank you for your help and understanding... Only the bqi language code is enough and there is no need for the country code...
> 
> If the country code is mandatory, consider "ir"...

k

**Comment by hosseinabaspanah** [comment]
hello
Just to remind you, don't forget to merge this request...
@CodeWithTamim

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/pull/3952

**Pull request closed without merging**
