### PR TITLE
Outbound speed

### PR DESCRIPTION
**Pull request by yuhan6665**
- first commit: show separately for "proxy" and "direct" traffic stats in notification
- second: update notification icon based on traffic usage

### CODE REVIEW

**Comment by appstestacc** [comment]
我用的是自定义配置，经过这个更新V2RayNG显示数据流速永远是0

**Comment by appstestacc** [comment]
@yuhan6665
华为P9 Emui4.1 不论是不是自定义，通知栏都不再显示速度（不是速度0，而是彻底没有速度显示）

**Comment by yuhan6665** [comment]
@appstestacc can you check if "Enable speed display" is on in settings? Also, when you use the proxy, does the notification icon change?

**Comment by appstestacc** [comment]
@yuhan6665
速度显示选项已经勾选，屏幕顶上完全没有V的图标，仅在下拉通知菜单里有一个不显示速度的条目。
（PS. 这个手机是在国外买的，会不会跟这个有关系...?）

**Comment by appstestacc** [comment]
Screenshot_2020-07-29-13-10-17
IMG_20200729_131122

**Comment by yuhan6665** [comment]
Hmm, looks like this phone has a custom notification UI. Does it support 多行文本 or has some setting you can change? I see emui default UI should support like
https://developer.huawei.com/consumer/cn/doc/HMSCore-Guides-V5/android-large-text-style-0000001050042081-V5

**Comment by appstestacc** [comment]
不太确定... 印象中先前的版本可以在下拉通知菜单里显示速度的

**Comment by yuhan6665** [comment]
@appstestacc Can you post a screenshot for what the notification looks like with older version of v2rayNG? I can potentially add a fix for supporting this device.

**Comment by appstestacc** [comment]
IMG_20200731_190510
@yuhan6665

**Comment by yuhan6665** [comment]
@appstestacc Will you willing to do a quick test with the following test apk? You will need to uninstall the current version first.
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/app-universal-debug.apk

**Comment by appstestacc** [comment]
Screenshot_2020-08-02-11-38-03

速度显示已修好，非常感谢！ 但是我自己之前用的自定义配置一启动就闪退，可能是因为什么格式要求改变导致不兼容（app自动导出的配置json没问题）。抱歉暂时没有更多时间仔细测试，建议把最近几次更新导致的自定义配置格式要求变更作个汇总说明。非常感谢！
@yuhan6665

**Comment by yuhan6665** [comment]
Sounds good. I will push a PR soon. Don't worry about the crash. It is due to the legacy geoip and geosite files with bypassing china. It won't happen in release version.

**Pull request merged**
