### PR TITLE
action to check build error

### PR DESCRIPTION
**Pull request by rurirei**
example: https://github.com/rurirei/v2rayNG/runs/1298737796

### CODE REVIEW

**Comment by rurirei** [comment]
@yuhan6665 to fix bug of commandline gradle needs to specify latest ndkVersion, could i push it there? https://github.com/rurirei/v2rayNG/commit/cfe6299 https://stackoverflow.com/questions/60404457/no-version-of-ndk-matched-the-requested-version

**Comment by yuhan6665** [comment]
@rurirei what is the error message you see without this ndk line? I only see a successful build in https://github.com/rurirei/v2rayNG/actions

**Comment by rurirei** [comment]
> @rurirei what is the error message you see without this ndk line? I only see a successful build in https://github.com/rurirei/v2rayNG/actions

reproducing, check action list later.

**Comment by rurirei** [comment]
reproduced https://github.com/rurirei/v2rayNG/actions/runs/324596802

**Comment by yuhan6665** [comment]
Maybe it is better to set `ANDROID_NDK_HOME` to `${ANDROID_HOME}/ndk/21.3.6528147` in your workflow?

**Comment by rurirei** [comment]
> Maybe it is better to set `ANDROID_NDK_HOME` to `${ANDROID_HOME}/ndk/21.3.6528147` in your workflow?

failed to try this.

**Comment by rurirei** [comment]
@yuhan6665 if interested in this, create a separate branch to run actions like https://github.com/rurirei/Kitsunebi/tree/debug

**Comment by yuhan6665** [comment]
Thanks I will plan to add CI

**Pull request closed without merging**
