### PR TITLE
build tun2socks  with ndk

### PR DESCRIPTION
**Pull request by blackier**
build tun2socks  with ndk

### CODE REVIEW

**Comment by blackier** [comment]
verfied, and solve death loop while tun2socks launch failed.

**Comment by rurirei** [comment]
not necessary i thought.

**Comment by blackier** [comment]
> not necessary i thought.

This is a more convenient and understandable way to use tun2sock instead of just using a binary.

**Comment by 2dust** [comment]
Please PR the V2RayVpnService.kt part alone

**Pull request closed without merging**
