### PR TITLE
Update build.yml

### PR DESCRIPTION
**Pull request by ghost**
github not use Flavors.

### CODE REVIEW

**Comment by UjuiUjuMandan** [comment]
@2dust Sorry, please revert this. It's necessary for Reproducible Builds.

The workflow is like this:

1. GitHub Actions builds and uploads the APKs of both flavors to releases, one is with `-fdroid` suffix, the other is not.
2. fdroidserver builds the APKs of `fdroid` flavors.
3. fdroidserver fetches your APKs with `-fdroid` suffix from GitHub Releases.
4. fdroidserver compares them. If passed, releases it with copying your signatures.

**Comment by UjuiUjuMandan** [comment]
The `sed` patching is really unnecessary; I have only seen downstream patches of upstream; how opposite?

**Comment by UjuiUjuMandan** [comment]
I'll revert that after the veery slow `diffoscope` completed.

**Comment by ghost** [comment]
😂a little trouble, all right.

**Pull request merged**
