### PR TITLE
add auto update subscriptions with interval

### PR DESCRIPTION
**Pull request by hadi-norouzi**
#1910 #2403 #2225 #2031

### CODE REVIEW

**Comment by Ali-ph** [comment]
Hi dear
How can i use it 
Can you expalin that simply?

**Comment by hadi-norouzi** [comment]
> Hi dear How can i use it Can you expalin that simply?

You need to build an apk from my fork or just wait until owner merge my pull request to this repo.
You need to turn on auto update from V2rayNG setting and choose your interval and turn on every subscription you want to automatically update.

**Comment by Ali-ph** [comment]
How can we help support to see your message faster?


Sent from my Galaxy



-------- Original message --------
From: Hadi Norouzi ***@***.***>
Date: 18/08/2023 00:53 (GMT+03:30)
To: 2dust/v2rayNG ***@***.***>
Cc: Ali-ph ***@***.***>, Comment ***@***.***>
Subject: Re: [2dust/v2rayNG] add auto update subscriptions with interval (PR #2471)


Hi dear How can i use it Can you expalin that simply?

You need to build an apk from my fork or just wait until owner merge my pull request to this repo.
You need to turn on auto update from V2rayNG setting and choose your interval and turn on every subscription you want to automatically update.

**Comment by ssmetall** [comment]
Hello and thank you dear Hadi, automatic update is really an important need, I think v2rayng is coded by yuhan6665, please mention it there https://github.com/yuhan6665/v2rayNG/releases

and telegram id is :
@yuhan6665

**Comment by imanmoghimiq30** [comment]
Hi Hadi
Much appreciated for your great job.
Could you please work on a feature that search between config and find lowest ping server?
I think combination of both (auto update and find best server) would be great.
Best regards

**Comment by mshaterzadeh** [comment]
This option is very useful, but in my opinion, it is better to do the update subscription link when the program is opened and actually before turning on the service. like this "Streisand" App in ios . Because when the proxies are not working properly, the update will not be done properly. Thanks Hadi.

**Comment by StayAway32** [comment]
hello merge the auto sub update please its hardly needed
just allow the server to choose the interval between updates in case target server got blocked so we can just force the client to send update request
thanks alot

**Comment by cuynu** [comment]
thanks for this useful feature, i will add that on my v2rayNG fork haha

**Comment by iamtheted** [comment]
> > Hi dear How can i use it Can you expalin that simply?
> 
> You need to build an apk from my fork or just wait until owner merge my pull request to this repo. You need to turn on auto update from V2rayNG setting and choose your interval and turn on every subscription you want to automatically update.

Hi Hadi Jan,
Hope you're doing alright.

This is still too complicated. 
Turning on auto update and choosing which subscription link to include.
This option is indeed quite useful since it makes it easier to update for old people and people who don't know how to do these things, so wouldn't be better to add auto update by default? like NekoBox. 

Please let me know what your thoughts are on this matter
Thanks a lot bro

**Comment by StayAway32** [comment]
great opinion
it is infact complicated because going to setting and turning on things + adding interval for casual people is way more complicated than simply hitting 3 dots and choosing last option which is update subscription

if possible just put it on auto update and let the server decide the interval ( cause most panels have this option for admin to choose update interval )

or just simply put the default on 24h which is not too low nor too high
thanks alot again

**Comment by tw20160623** [comment]
你好，请帮我取消订阅！谢谢

StayAway32 ***@***.***> 於 2023年9月11日 週一 20:56 寫道：

**Comment by KAJOOSH** [comment]
Please put the build file (apk). Apparently, it is not clear when this request will be approved.
@hadi-norouzi

**Comment by hadi-norouzi** [comment]
> Please put the build file (apk). Apparently, it is not clear when this request will be approved. @hadi-norouzi

Now you can download an apk with auto-update feature from my repo, please test it and give me feedback.

**Comment by ssmetall** [comment]
> > Please put the build file (apk). Apparently, it is not clear when this request will be approved. @hadi-norouzi
> 
> Now you can download an apk with auto-update feature from my repo, please test it and give me feedback.

thanks hadi

**Comment by ssmetall** [comment]
> > Please put the build file (apk). Apparently, it is not clear when this request will be approved. @hadi-norouzi
> 
> Now you can download an apk with auto-update feature from my repo, please test it and give me feedback.

Hi Hadi, the build you released has a signature problem and a malicious program has been detected, is it possible to post the signed build?

**Comment by iamtheted** [comment]
> > Please put the build file (apk). Apparently, it is not clear when this request will be approved. @hadi-norouzi
> 
> Now you can download an apk with auto-update feature from my repo, please test it and give me feedback.

Hello again Hadi Jan, 
Hope you're doing alright!

I truly appreciate you for taking the time and making this happen!
I have been waiting for this for a very long time. You're just amazing. 
But the Auto update box is unchecked by default which makes the deep link not to work.
The deep link adds the sub link into v2rayNG and since the auto update is not checked by default, then people have to update manually or check that box which is again a lot of work for casual people who are not familiar with these settings which are quite easy.

So, I was wondering if you'd consider changing the auto update box to checked by default? 
I do appreciate you for all your time and effort, fantastic work! I love the lite theme as well.

Please update us on this matter if it's possible.
Thank you so very much Hadi Jan 💙

**Comment by KAJOOSH** [comment]
For the question, why is it not put in the main project?
This feature is very necessary.

@2dust Please add in

**Comment by cuynu** [comment]
> For the question, why is it not put in the main project? This feature is very necessary.
> 
> @2dust Please add in

2dust? they only want to fix bugs inside app and almost NEVER merge any new feature implemented by other than (yuhan6665) so far as i know. if u want that feature, fork own and merge yourself

**Comment by iamtheted** [comment]
> > For the question, why is it not put in the main project? This feature is very necessary.
> > @2dust Please add in
> 
> 2dust? they only want to fix bugs inside app and almost NEVER merge any new feature implemented by other than (yuhan6665) so far as i know. if u want that feature, fork own and merge yourself

I have no idea what has taken them so long about this PR.
This is simply a useful feature so why don't they merge this? 
Check the pull requests that are closed, most of them have been merged.

**Comment by StayAway32** [comment]
i think this feature is off by default as someone already mentioned and well most people wont even bother or know to turn it on

**Comment by iamtheted** [comment]
> i think this feature is off by default as someone already mentioned and well most people wont even bother or know to turn it on

Let's change the default then, who defines what default has to be? :/

**Comment by burjuyz** [comment]
Please make the subscription preferences by default ON.
And update every 12 hours for example...

**Comment by hawshemi** [comment]
**This is highly requested by users.**
Please review @2dust @yuhan6665

**Comment by MrVb0** [comment]
Please make the subscription preferences by default ON.
And update every 12 hours for example...

**Comment by MrVb0** [comment]
up!
please accept this pr

**Comment by iamtheted** [comment]
This project has been updated after this PR, so it literally means they have seen this and still chose not to merge it and I'm wondering why that is.

**Comment by cuynu** [comment]
> This project has been updated after this PR, so it literally means they have seen this and still chose not to merge it and I'm wondering why that is.

there are conflicts between PR and this repo, but i just merged on my fork and it works fine

**Comment by ssmetall** [comment]
hora🎷🎷 , thanks 2dust

**Comment by mmrabbani** [comment]
@hadi-norouzi 
This feature is not working anymore in the recent version of the app. Maybe there is some conflict with later commits.
Could you please take a look at that.
If updating with an interval cannot work well (because of the android power saving option or anything else), updating at the opening of the app can also be an option.

**Review by abolfzlfr111 — APPROVED** [review]

**Pull request merged**
