### PR TITLE
Add external geofile replacement help

### PR DESCRIPTION
**Pull request by yuhan6665**
https://github.com/yuhan6665/v2rayNG/tree/ext-geo

### CODE REVIEW

**Comment by rurirei** [comment]
you need to use SAF to provide files, as external app dir is restricted to access on api 30

**Comment by yuhan6665** [comment]
> you need to use SAF to provide files, as external app dir is restricted to access on api 30

You are taking about deprecation of https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String)?
The proposal is to use https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)

**Comment by rurirei** [comment]
@yuhan6665 no, study on new storage on Android 11please.

**Comment by yuhan6665** [comment]
> @yuhan6665 no, study on new storage on Android 11please.

@rurirei thanks for your information. I read the [document](https://developer.android.com/training/data-storage) and did some test on Android 11 emulator. So v2rayNG can still access `Android/data/com.v2ray.ang/` but other apps (including system file viewer) can't. That means user will not be able to update this file.

Looks like we have no other choice but to add a File chooser for getting user's geofiles. Fortunately we can keep building on top of #662. I think it's best to add another item in advanced settings. Thoughts? @2dust

**Comment by ayanamist** [comment]
按 #172 的情况，这里的代码已经不是最新了，这个PR可能没有什么意义……

**Comment by pansila** [comment]
> > @yuhan6665 no, study on new storage on Android 11please.
> 
> @rurirei thanks for your information. I read the [document](https://developer.android.com/training/data-storage) and did some test on Android 11 emulator. So v2rayNG can still access `Android/data/com.v2ray.ang/` but other apps (including system file viewer) can't. That means user will not be able to update this file.
> 
> Looks like we have no other choice but to add a File chooser for getting user's geofiles. Fortunately we can keep building on top of #662. I think it's best to add another item in advanced settings. Thoughts? @2dust

Why adding a custom data updater hasn't been added in the latest V2rayNG(1.6.15)? Is there any further restriction from Android 11?

**Pull request merged**
