### PR TITLE
Add support to transport for shadowsocks

### LINKED ISSUE #2849: feat request: 希望添加Shadowsocks的混淆以及SIP002的支持
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
v2rayN目前已支持Shadowsocks+v2ray-plugin混淆（即transport部分可以设为tcp+http混淆/ws/quic），从技术上来说v2rayNG也完全可以支持Shadowsocks+混淆，希望可以添加这一支持

### 实际行为
目前v2rayNG的Shadowsocks协议仅支持传统的原生Shadowsocks，即便在订阅链接中加入SIP002包含混淆参数的订阅，v2rayNG在解析时依旧会将混淆参数舍去

### 复现方法
无

### 日志信息
无

### PR DESCRIPTION
**Pull request by Utaea**
This pr closes https://github.com/2dust/v2rayNG/issues/2849

### CODE REVIEW

**Comment by 2dust** [comment]
Has the test passed?

**Comment by Utaea** [comment]
The code can be successfully built into an APK. And I've done some simple testing, like parsing the share link with different plugin/plugin-opts or manually adding a shadowsocks server with custom transport settings and then launching v2ray, everything seems to be working fine.

**Comment by 2dust** [comment]
Thank you for your PR
Although adding this function to shadowsocks does not make much sense

**Comment by Utaea** [comment]
> Thank you for your PR Although adding this function to shadowsocks does not make much sense

I do know that this doesn't help much, but since v2rayN supports parsing plugin options in SIP002 share link, it also supports transport for shadowsocks, it's not a bad idea to bring this feature to v2rayNG. Anyway, thanks for your recognition.

**Comment by dill-shower** [comment]
Can we add support for utls on VrayNG if we using Ss+xray-plugin? Xray plugin currently actual version and can be used and we already use xray core 

https://github.com/teddysun/xray-plugin

**Comment by Nexus2010** [comment]
> 代码可以成功构建到 APK 中。我已经做了一些简单的测试，比如使用不同的 plugin/plugin-opts 解析共享链接，或者手动添加具有自定义传输设置的 shadowsocks 服务器，然后启动 v2ray，一切似乎都运行正常。

在最新版本中，手动添加shadowsocks配置时，在transport的各个选项中我真没找到v2ray-plugin这个。请教下具体怎么配置，谢谢！

**Pull request merged**
