### PR TITLE
Add Bakhtiari language support and fix implementation issues

### PR DESCRIPTION
**Pull request by codewithtamim**
This commit improves the Bakhtiari language support by addressing issues from PR [#3927](https://github.com/2dust/v2rayNG/pull/3927), where the initial implementation had incorrect file placements and lacked necessary changes for functionality.

- Integrated `strings.xml` into the correct `values-bqi-rIR` directory.
- Updated the `Language` enum to include `BAKHTIARI("bqi-rIR")`.
- Modified the `getLocale()` function to handle Bakhtiari with `Locale("bqi", "IR")`.
- Added Bakhtiari to the `language_select` string-array using its native script: `<item>بختیاری</item>`.
- Updated the `language_select_value` string-array to include `<item>bqi-rIR</item>`.

Verified that the language switching works correctly. For grammatical or translation accuracy, a native speaker's review is needed.

@hosseinabaspanah, since I assume Bakhtiari is your native language, could you please review the translations to ensure accuracy?

### CODE REVIEW

**Comment by 2dust** [comment]
Which country is this language spoken in?

**Comment by codewithtamim** [comment]
> Which country is this language spoken in?

It's spoken in iran as @hosseinabaspanah told me.

**Comment by hosseinabaspanah** [comment]
> Which country is this language spoken in?

Iran

**Comment by hosseinabaspanah** [comment]
Please rename بختیاری to لۊری بختیاری

**Comment by codewithtamim** [comment]
> Please rename بختیاری to لۊری بختیاری

do pr

**Pull request merged**
