### PR TITLE
Fix UI touch issues for Android TV

### PR DESCRIPTION
**Pull request by yuhan6665**
Fix the following screens
- Main activity
- Subscription activity
- Bypass per-app settings activity
Make sure the button is focusable and have a good background for highlighting. Fix small icon touch and layout padding in recyclerView.
I've tested on Android TV emulators.

### CODE REVIEW

**Comment by hertzr** [comment]
已经测试最新版，遥控器还是无法选择节点，其他问题不大，主要就是节点选择不了，用遥控器点节点会闪一下但并不能选中

**Comment by yuhan6665** [comment]
@hertzr note this hasn't been merge nor release yet.
@2dust Thanks for merging my other changes! Let me know if you have any concern over this change or you have any suggestion about it.

**Comment by 2dust** [comment]
Not enough time to merge tests, please wait

**Comment by halfcrazy** [comment]
节点列表较多时，右下角连接按钮不是很好选中。

**Comment by 2dust** [comment]
TV尽量导入个位数节点比较合适

**Comment by zazitufu** [comment]
今天在miboxs上面试了这个1.2.5版本。就适配TV方面，提几个建议，望能采纳。

1，在配置文件上下选择到了需要的节点之后，第一次按确定键，会进行“选择此节点”的操作。第二次按确定键，会弹出左侧栏。希望能在左侧栏里加两个按钮，“启动/停止”的按钮。“测速”的按钮。这样更方便使用TV遥控器进行操作。
   因为我发现右下连接按钮确实不是很好选中。要很仔细看才能发现有阴影到了哪个连接按钮。要是在弹出左侧栏里进行操作会比较方便遥控器用户。

2，上下选择节点配置文件时候，焦点的阴影颜色深一点。

3，如果安卓TV遥控器的操作规则跟普通安卓手机的操作规则差异太大，不太合适用一个APP统一完成，或者考虑一下放个TV专用版本？

**Comment by xenstar** [comment]
On Android TV it works but with the remote, I can't go to the "connect" button. I have to use a USB mouse, then click on connect. I hope you will fix this, so we can easily use v2ray on Android TV too.  Please see if you can do anything regarding this to fix this small bug.

**Pull request merged**
